maratona/urls.py
from django.urls import path

from . import views

app_name = 'maratona'
urlpatterns = [
    # ex: /maratona/
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail')
]

maratonafc3_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='maratona:index')),
    path('maratona/', include('maratona.urls'))
]

maratona/models.py
from django.db import models


class Aula(models.Model):
    title = models.CharField(max_length=200)
    image_url = models.TextField('image url')
    video_url = models.TextField('video url', default=None, blank=True, null=True)
    live_date = models.DateTimeField('live date')

    def __str__(self):
        return self.title

maratona/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from django.views import generic

from .models import Aula


class IndexView(generic.ListView):
    template_name = 'maratona/index.html'
    context_object_name = 'latest_aulas_list'

    def get_queryset(self):
        """Return the last 10 published aulas."""
        return Aula.objects.order_by('live_date')[:10]


class DetailView(generic.DetailView):
    model = Aula
    template_name = 'maratona/detail.html'

maratona/templates/maratona/base.html
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Maratona Full Cycle 3.0</title>

    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#ffcd25">

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,700,600" rel="stylesheet" as="style"
          onload="this.rel='stylesheet'" type="text/css">

    <link rel="stylesheet" href="{% static 'maratona/styles/site.css' %}">
    <link rel="stylesheet" href="{% static 'maratona/styles/classes.css' %}">

    {% block head %}
    {% endblock %}

<body>
<div id="fb-root" class=" fb_reset">
    <div style="position: absolute; top: -10000px; width: 0px; height: 0px;">
        <div></div>
    </div>
</div>

<main class="page">

    <div class="container-page">

        <div class="menu">
            <a href="{% url 'maratona:index' %}" title="Home" class="item-menu-logo">
                <img src="{% static 'maratona/images/logo-top.png' %}" alt="logo" class="logo">
            </a>

            <div class="list-items">
                <a title="Home" class="item-menu disabled">
                    <span class="icon-m-home"></span>
                    <p>Home</p>
                </a>
                <a href="{% url 'maratona:index' %}" title="Aulas" class="item-menu active">
                    <span class="icon-m-curso"></span>
                    <p>Aulas</p>
                </a>
                <a title="Lives" class="item-menu disabled">
                    <span class="icon-m-relogio1"></span>
                    <p>Lives</p>
                </a>
                <a title="Desafios" class="item-menu disabled">
                    <span class="icon-m-desafios"></span>
                    <p>Desafios</p>
                </a>

                <a title="Comunidade" class="item-menu disabled">
                    <span class="icon-m-comunidade"></span>
                    <p>Comunidade</p>
                </a>

                <a title="Depoimentos" class="item-menu disabled">
                    <span class="icon-m-depoimentos"></span>
                    <p>Depoimentos</p>
                </a>

                <a title="Curso Full Cycle" class="item-menu disabled">
                    <span class="icon-m-fullcycle"></span>
                    <p>Curso Full Cycle</p>
                </a>
            </div>
        </div>

        <div class="content">


            <nav class="navbar-main">

                <div class="container container-nav">
                    <a href="/" title="">
                        <img src="{% static 'maratona/images/logo-fullcycle.png' %}" alt="logo" class="logo img-fluid">
                    </a>

                    <div class="items-nav">
                        <a href="https://www.linkedin.com/in/uiltonoliveira/" target="_blank"
                           title="Linkedin" class="item linkedin">
                            <span class="icon-linkedin2"></span>
                        </a>

                        <a href="https://github.com/DarkSupremo?tab=repositories&q=maratonafc3" target="_blank"
                           title="Repositórios da Maratona Full Cycle 3.0" class="item">
                            <span class="icon-m-git1"></span>
                        </a>

                        <a href="https://t.me/devfullcycle" target="_blank" title="Participe de nosso Canal no Telegram"
                           class="item">
                            <span class="icon-m-telegram"></span>
                        </a>
                    </div>
                </div>

            </nav>


            <div class="info-top">
                <div class="container">
                    <a href="mailto:uilton.dev@gmail.com" class="link-info">
                        <span class="icon-mail"></span>
                        <p>uilton.dev@gmail.com</p>
                    </a>
                </div>
            </div>

            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>


<footer id="footer" class="footer-default">
    <div class="copy">
        <div class="container">
            <div class="info">
                <p>
                    © CODE.education 2014 - 2020 - Todos os direitos reservados
                </p>
            </div>
        </div>
    </div>
</footer>

</body>
</html>

maratona/templates/maratona/detail.html
{% extends 'maratona/base.html' %}
{% load static %}

{% block head %}

{% endblock %}

{% block content %}

    <div class="page-classes-details">
        <section class="classes">

            <div class="container">
                <h1>Aula</h1>
                <div class="row">
                    <article class="content">
                        <div class="col-12 col-xl-11">
                            <div class="title-content">
                                <span>{{ aula.live_date|date:"d/m" }}</span>
                                <h2>{{ aula.title }}</h2>
                            </div>

                            <div class="article-content">
                                <div class="container-title"></div>

                                <div class="container-content">
                                    <div class="content-type">
                                        <div class="embed-responsive embed-responsive-16by9">
                                            <iframe src="{{ aula.video_url }}?rel=0&amp;showinfo=0&amp;autoplay=0"
                                                    width="100%" height="100%" frameborder="0"
                                                    allow="autoplay; encrypted-media"
                                                    allowfullscreen="">
                                            </iframe>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>

        </section>
    </div>
{% endblock %}

maratona/templates/maratona/index.html
{% extends 'maratona/base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
    {% now "Y-m-d" as todays_date %}

    <div class="page-classes-index">
        <section class="classes">

            <div class="container">
                <h1>Aulas</h1>

                <div class="row">
                    {% if latest_aulas_list %}
                        {% for aula in latest_aulas_list %}

                            <article class="col-12 col-lg-6">
                                {% if aula.video_url %}
                                    <a href="{% url 'maratona:detail' aula.id %}" class="box activate">
                                {% else %}
                                    <a class="box disabled">
                                {% endif %}
                                    <div class="content">
                                        <img src="{{ aula.image_url }}"
                                             alt="{{ aula.title }}" class="img-fluid">

                                        <div class="content-title">
                                            <h2>{{ aula.title }}</h2>
                                            <div class="info">
                                                <p>
                                                    <span class="icon-m-play2"></span>
                                                    Assistir
                                                </p>
                                                <p>
                                                    <span class="icon-m-fullcycle"></span>
                                                    {{ aula.live_date|date:"d/m" }}

                                                    {% if aula.video_url %}
                                                       <span class="in-ar">No ar</span>
                                                    {% endif %}

                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </article>
                        {% endfor %}
                    {% else %}
                        <p>Nenhuma aula disponível.</p>
                    {% endif %}
                </div>
            </div>

        </section>
    </div>
{% endblock %}